# Generated by Django 4.0.2 on 2022-09-11 14:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0006_alter_item_created_on_alter_orders_placed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 11, 14, 24, 53, 232916)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='placed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 11, 14, 24, 53, 232916)),
        ),
    ]
