# Generated by Django 4.0.2 on 2022-09-11 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_alter_item_created_by_alter_item_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 11, 15, 38, 38, 18765)),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='placed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 11, 15, 38, 38, 20753)),
        ),
    ]
