# Generated by Django 4.0.2 on 2022-09-11 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_alter_item_created_on_alter_item_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 11, 15, 39, 23, 990214)),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='placed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 11, 15, 39, 23, 991216)),
        ),
    ]
