# Generated by Django 4.0.2 on 2022-09-16 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0016_alter_donate_donated_on_alter_item_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='doanted_by',
            new_name='donated_by',
        ),
        migrations.AlterField(
            model_name='donate',
            name='donated_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 22, 58, 15, 324757)),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 16, 22, 58, 15, 323756)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='placed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 16, 22, 58, 15, 324757)),
        ),
    ]
