# Generated by Django 4.0.2 on 2022-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0017_rename_doanted_by_donate_donated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='donated_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='placed_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
