# Generated by Django 4.0.2 on 2022-10-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0019_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('food', 'FOOD'), ('clothing', 'CLOTHING'), ('utensils', 'UTENSILS'), ('books', 'BOOKS'), ('Others', 'OTHERS')], default='clothing', max_length=30),
        ),
    ]
