# Generated by Django 4.0.2 on 2022-08-31 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(default='0', max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('city', models.CharField(default='', max_length=16)),
                ('state', models.CharField(default='', max_length=16)),
                ('zipcode', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('food', 'FOOD'), ('clothing', 'CLOTHING')], default='clothing', max_length=30)),
                ('cost', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(blank=True, default='2022-31-08 13:14:38')),
                ('image', models.ImageField(default='', upload_to='home/images')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
