# Generated by Django 4.0.2 on 2022-08-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(blank=True, default='2022-31-08 13:15:54'),
        ),
    ]
