# Generated by Django 4.0.2 on 2022-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_item_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(blank=True, default='2022-31-08 14:03:08'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='login/images'),
        ),
    ]
