# Generated by Django 4.0.2 on 2022-08-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_item_created_on_alter_item_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
