# Generated by Django 4.0.2 on 2022-09-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='password',
        ),
    ]
