# Generated by Django 4.0.2 on 2022-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='somwethig',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
