# Generated by Django 4.0.2 on 2022-09-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_somwethig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='somwethig',
        ),
    ]
